EDA basico
MentoriaPloomber/RAG_HayStack_QA pull request #4
Opened 2023-10-08 12:00 UTC by caropass

EDA basico del archivo de la Relatoria: Metadata.csv. Tambien tiene desagregacion de columnas de la Ciudad donde inició la demanda y donde culminó.

2023-10-11 00:34 UTC, lfunderburk requested changes
Hola @caropass 

Interesante exploracion, por favor trabaja con Eduardo y el equipo en la extraccion de datos. Veo que tienes funcionalidad para limpiar los datos. Por favor crea funciones de Python para el codigo que limpia la metadata. 

Un blog que puedes usar para escribir funciones robustas (clic derecho y traduce a espanol)

https://ploomber-sql.readthedocs.io/en/latest/packaging-your-sql-project/intro-to-python-scripting-and-pipelines.html

2023-10-17 19:05 UTC, lfunderburk commented
Hola Carolina,

Quieres agregar el codigo a main? No entendi por que se cerro

2023-10-17 19:10 UTC, caropass commented
Agregué otro archivo .ipynb para dejar sin efecto el anterior. Porque en definitiva con el archivo denominado Metadata no vamos a trabajar, en realidad es solo para tener una idea del area de estudio. Nuestros archivos importantes son los descargados con el proceso de scraping, que en definitiva son las sentencias que va a ingerir nuestro sistema de QA.

2023-10-17 22:26 UTC, lfunderburk approved these changes
Entiendo
Por favor trabajen con Anuar para poner sus cuadernos y trabajo en el repo

2023-10-17 22:26 UTC, merged