Cambios para review de extraccion
MentoriaPloomber/RAG_HayStack_QA pull request #7
Opened 2023-10-11 05:58 UTC by SergioRodMa

Proceso para la descarga archivos y conversion a formato txt

2023-10-11 06:08 UTC, lfunderburk requested changes
Parece que aun hay pasos manuales para la extraccion

El comentario aun es relevante? Tambien veo codigo comentado sobre archivos drive. Idealmente queremos remover pasos manuales. Hay algun modo de automatizar la extraccion del archivo "relatoria_corte_Constitucional_20230922.xls" o Metadata.csv? O eso ya se completo con extract.py y solo hay que limpiar

```
#Proceso de creacion del archivo de metadata para la 
#Extraccion de Links de descarga e informacion de los archivos
# Para correrlo es necesario tener el archivo de relatoria corte

# df=pd.read_html("relatoria_corte_Constitucional_20230922.xls")[0]

# with open('relatoria_corte_Constitucional_20230922.xls','r',encoding='utf-8') as file:
#     content=file.read()

# soup=BeautifulSoup(content,"html.parser")
# href_tag=soup.find_all('a', href=True)
# links=[]
# for tag in href_tag:
#     links.append((tag.text,tag['href']))
# df_links=pd.DataFrame(links, columns =['Providencia', 'Link'])
# df_descarga=df.merge(df_links,how="left",left_on="Providencia",right_on="Providencia").set_index("#")
# df_descarga["Link_descarga"]=df_descarga["Link"].str.replace("relatoria","sentencias",regex=False).str.replace("htm","rtf",regex=False)
# df_descarga.to_csv("Metadata.csv",sep="|",index=None)
```

2023-10-11 15:21 UTC, SergioRodMa commented
Hola Laura actualmente no hemos encontrado una forma viable de automatizar la descarga del archivo "relatoria_corte_Constitucional_20230922.xls" ya que se necesita entrar a una pagina, filtrar la informacion y hacer algunos clicks manuales. Hemos explorado utilizat Selenium, sin embargo esto implicaria tener que instalar google chrome en el contenedor para poder utilizarlo y replicar los clicks. Debido a esto decidimos conservar el archivo "metadata.csv" en la carpeta del proceso, que es practicamente el archivo "relatoria_corte_Constitucional_20230922.xls" ya procesado con las direcciones de descarga de los documentos que vamos a utilizar como dataset

2023-10-11 15:22 UTC, SergioRodMa commented
Como alternativa tambien podriamos montar el archivo metadata.csv en un repositorio publico con informacion mas detallada para su generacion y mandarlo a llamar en el pipeline (descargarlo). Asi evitariamos tenerlo en la carpeta del proceso

2023-10-11 15:30 UTC, lfunderburk commented
Hola Sergio,

Entiendo. Que les parece initializar una base de dates duckdb, poner el archivo Metadata ahi, subir la base de datos a la nube usando mother duck y llamar Los datos desde el script? 

Que tan seguido necesitan cambiar Los datos? Me puedes compartir la Liga al sitio web donde descargas el archivo excel?

2023-10-11 16:23 UTC, SergioRodMa commented
Hola Laura,
El archivo lo generamos en el siguiente enlace [https://www.corteconstitucional.gov.co/relatoria/](https://www.corteconstitucional.gov.co/relatoria/) y utilizamos los filtros de año, para despues darle a descargar al excel.
En cuanto a que tan seguido cambian los datos al ser sentencias todos los meses se agregan nuevas. Sin embargo, estamos utilizando todas las sentencias generadas en 2022 para el modelo LLM

2023-10-12 18:43 UTC, lfunderburk commented
Ok
Pueden entonces crear un README.md en la misma carpeta que src

Muevan comentarios sobre su proceso ahi

Por favor limpien el codigo para que no tenga esos comentarios

2023-10-12 18:53 UTC, lfunderburk requested changes
@SergioRodMa tus scripts parecen estar listos

Por favor:

inicializa tu pipeline de ploomber en el archivo pipeline.yaml (este archivo se encuentra en el nivel base del repositorio)

ahorita el pipeline tiene

```
tasks:
  - source: src/etl/extract.py
    product:
      nb: src/products/extract-pipeline.ipynb
      data: data.duckdb
```

Modifica eso para ejecutar tu script

Despues de eso, desde el nivel base del repositorio, ejecuta

```
poetry run ploomber build
```

si estas usando poetry o simplemente

```
ploomber build
```

si tienes tu ambiente hactoberfest-env activo

2023-10-15 12:10 UTC, closed without merging